import { Annotation } from "@langchain/langgraph";
import {
  AgentAssistedRuleResult,
  AgentPromptPayload,
  AgentRunStatus,
  AssistedRuleCandidate,
  CaseInput,
  ConstraintSummary,
  EvidenceSummary,
  FeatureExtraction,
  LoadedRubricSnapshot,
  RuleEvidenceIndex,
  RuleAuditResult,
  RuleViolation,
  ScoreComputation,
  TaskType,
} from "../types.js";

export const ScoreState = Annotation.Root({
  caseInput: Annotation<CaseInput>(),
  caseDir: Annotation<string>(),
  originalPromptText: Annotation<string>(),
  constraintSummary: Annotation<ConstraintSummary>(),
  taskType: Annotation<TaskType>(),
  featureExtraction: Annotation<FeatureExtraction>(),
  rubricSnapshot: Annotation<LoadedRubricSnapshot>(),
  ruleAuditResults: Annotation<RuleAuditResult[]>(),
  ruleEvidenceIndex: Annotation<RuleEvidenceIndex>(),
  deterministicRuleResults: Annotation<RuleAuditResult[]>(),
  assistedRuleCandidates: Annotation<AssistedRuleCandidate[]>(),
  agentPromptPayload: Annotation<AgentPromptPayload>(),
  agentPromptText: Annotation<string>(),
  agentRawOutputText: Annotation<string>(),
  agentAssistedRuleResults: Annotation<AgentAssistedRuleResult>(),
  agentRunStatus: Annotation<AgentRunStatus>(),
  mergedRuleAuditResults: Annotation<RuleAuditResult[]>(),
  ruleViolations: Annotation<RuleViolation[]>(),
  evidenceSummary: Annotation<EvidenceSummary>(),
  scoreComputation: Annotation<ScoreComputation>(),
  resultJson: Annotation<Record<string, unknown>>(),
  htmlReport: Annotation<string>(),
  uploadMessage: Annotation<string>(),
});

export type ScoreGraphState = typeof ScoreState.State;
