import { Annotation } from "@langchain/langgraph";
import {
  AgentAssistedRuleResult,
  AgentRunStatus,
  AgentBootstrapPayload,
  AssistedRuleCandidate,
  CaseInput,
  CaseAwareRunnerResult,
  CaseAwareAgentTurn,
  CaseRuleDefinition,
  CaseToolTraceItem,
  ConstraintSummary,
  EvidenceSummary,
  LoadedRubricSnapshot,
  ProjectStructureSummary,
  RemoteEvaluationTask,
  RubricScoringPayload,
  RubricScoringResult,
  RubricCaseAwareRunnerResult,
  RuleEvidenceIndex,
  RuleAuditResult,
  StaticRuleAuditResult,
  RuleViolation,
  ScoreComputation,
  TaskType,
} from "../types.js";

export const ScoreState = Annotation.Root({
  remoteTask: Annotation<RemoteEvaluationTask>(),
  caseInput: Annotation<CaseInput>(),
  sourceCasePath: Annotation<string>(),
  remoteTaskRootDir: Annotation<string>(),
  inputMode: Annotation<string>(),
  passthrough: Annotation<boolean>(),
  originalFileCount: Annotation<number>(),
  workspaceFileCount: Annotation<number>(),
  hasPatch: Annotation<boolean>(),
  caseDir: Annotation<string>(),
  effectivePatchPath: Annotation<string>(),
  caseRuleDefinitions: Annotation<CaseRuleDefinition[]>(),
  constraintSummary: Annotation<ConstraintSummary>(),
  workspaceProjectStructure: Annotation<ProjectStructureSummary>(),
  taskType: Annotation<TaskType>(),
  rubricSnapshot: Annotation<LoadedRubricSnapshot>(),
  staticRuleAuditResults: Annotation<StaticRuleAuditResult[]>(),
  ruleEvidenceIndex: Annotation<RuleEvidenceIndex>(),
  deterministicRuleResults: Annotation<RuleAuditResult[]>(),
  assistedRuleCandidates: Annotation<AssistedRuleCandidate[]>(),
  rubricScoringPayload: Annotation<RubricScoringPayload>(),
  rubricScoringPromptText: Annotation<string>(),
  rubricScoringResult: Annotation<RubricScoringResult>(),
  rubricAgentRunStatus: Annotation<AgentRunStatus>(),
  rubricAgentRawText: Annotation<string>(),
  rubricAgentRunnerResult: Annotation<RubricCaseAwareRunnerResult>(),
  rubricAgentTurns: Annotation<CaseAwareAgentTurn[]>(),
  rubricAgentToolTrace: Annotation<CaseToolTraceItem[]>(),
  rubricAgentRunnerMode: Annotation<"case_aware">(),
  ruleAgentBootstrapPayload: Annotation<AgentBootstrapPayload>(),
  ruleAgentPromptText: Annotation<string>(),
  ruleAgentRunnerResult: Annotation<CaseAwareRunnerResult>(),
  ruleAgentAssessmentResult: Annotation<AgentAssistedRuleResult>(),
  ruleAgentRunStatus: Annotation<AgentRunStatus>(),
  ruleAgentToolTrace: Annotation<CaseToolTraceItem[]>(),
  ruleAgentTurns: Annotation<CaseAwareAgentTurn[]>(),
  ruleAgentRunnerMode: Annotation<"case_aware">(),
  mergedRuleAuditResults: Annotation<RuleAuditResult[]>(),
  ruleViolations: Annotation<RuleViolation[]>(),
  evidenceSummary: Annotation<EvidenceSummary>(),
  scoreComputation: Annotation<ScoreComputation>(),
  resultJson: Annotation<Record<string, unknown>>(),
  htmlReport: Annotation<string>(),
  uploadMessage: Annotation<string>(),
});

export type ScoreGraphState = typeof ScoreState.State;
