import { Annotation } from "@langchain/langgraph";
import {
  AgentAssistedRuleResult,
  AgentRunStatus,
  AgentBootstrapPayload,
  AssistedRuleCandidate,
  CaseInput,
  CaseAwareRunnerResult,
  CaseAwareAgentTurn,
  CaseRuleDefinition,
  CaseToolTraceItem,
  ConstraintSummary,
  EvidenceSummary,
  FeatureExtraction,
  LoadedRubricSnapshot,
  RemoteEvaluationTask,
  RuleEvidenceIndex,
  RuleAuditResult,
  StaticRuleAuditResult,
  RuleViolation,
  ScoreComputation,
  TaskType,
} from "../types.js";

export const ScoreState = Annotation.Root({
  remoteTask: Annotation<RemoteEvaluationTask>(),
  caseInput: Annotation<CaseInput>(),
  sourceCasePath: Annotation<string>(),
  remoteTaskRootDir: Annotation<string>(),
  inputMode: Annotation<string>(),
  passthrough: Annotation<boolean>(),
  originalFileCount: Annotation<number>(),
  workspaceFileCount: Annotation<number>(),
  hasPatch: Annotation<boolean>(),
  caseDir: Annotation<string>(),
  effectivePatchPath: Annotation<string>(),
  caseRuleDefinitions: Annotation<CaseRuleDefinition[]>(),
  constraintSummary: Annotation<ConstraintSummary>(),
  taskType: Annotation<TaskType>(),
  featureExtraction: Annotation<FeatureExtraction>(),
  rubricSnapshot: Annotation<LoadedRubricSnapshot>(),
  staticRuleAuditResults: Annotation<StaticRuleAuditResult[]>(),
  ruleEvidenceIndex: Annotation<RuleEvidenceIndex>(),
  deterministicRuleResults: Annotation<RuleAuditResult[]>(),
  assistedRuleCandidates: Annotation<AssistedRuleCandidate[]>(),
  agentBootstrapPayload: Annotation<AgentBootstrapPayload>(),
  agentPromptText: Annotation<string>(),
  agentRunnerResult: Annotation<CaseAwareRunnerResult>(),
  agentAssistedRuleResults: Annotation<AgentAssistedRuleResult>(),
  agentRunStatus: Annotation<AgentRunStatus>(),
  agentToolTrace: Annotation<CaseToolTraceItem[]>(),
  agentTurns: Annotation<CaseAwareAgentTurn[]>(),
  agentRunnerMode: Annotation<"case_aware">(),
  mergedRuleAuditResults: Annotation<RuleAuditResult[]>(),
  ruleViolations: Annotation<RuleViolation[]>(),
  evidenceSummary: Annotation<EvidenceSummary>(),
  scoreComputation: Annotation<ScoreComputation>(),
  resultJson: Annotation<Record<string, unknown>>(),
  htmlReport: Annotation<string>(),
  uploadMessage: Annotation<string>(),
});

export type ScoreGraphState = typeof ScoreState.State;
